  env: "local"
  storage_path: "./storage/storage.db"
  http_server:
    address: "localhost:8082"
    timeout: 4s
    idle_timeout: 60s
    user: "myuser"
    password: "mypass"
  url_storage:
    address: "localhost:5051"
    timeout: 4s
    retries: 3